[project]
name = "imggrep"
version = "0.1.0"
dependencies = [
    "Pillow",
    "imagehash",
    "tqdm",
    "torch",
    "transformers",
    "sentencepiece",
    "protobuf",
]

[project.scripts]
imggrep = "imggrep.imggrep:main"

[project.optional-dependencies]
dev = [
    "ruff",
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
